[package]
name = "libdnsmasqplus"
version = "0.1.0"
authors = ["__JM_Joy__ <918734043@qq.com>"]
edition = "2018"

[lib]
name = "libdnsmasqplus"
path = "plus-src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
regex = "1.3.1"

